### ISSUE TITLE
Ejercicio_3_MUX

### ISSUE THREAD

**Issue by DOPALTEC** [DOPALTEC/Taller_Digitales_S2_2024#2]
Responsable: David

**Comment by DOPALTEC** [comment]
Testbench para un valor de 4 bits completado.

**Comment by DOPALTEC** [comment]
Restante:
-Autoverificar
-Test con 8bits
-Test con 16bits

**Comment by DOPALTEC** [comment]
Ejercicio_3 Completado. Se recomienda desde configuracion cambiar el tiempo de muestreo del testbech de 1000ns a 3000ns para observar completamente la prueba de las 3 configuraciones de bits (4,8,16)

**Comment by Maricv18** [comment]
Se implementó en FPGA
